name: Publish Docker Image

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs on pushes to tags like v1.0.0
  push:
    tags:
      - 'v*.*.*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # on git tag v*.*.* events, create tags: vX.Y.Z, vX.Y, vX, and latest
            type=semver,pattern={{version}},latest=true
            # on workflow_dispatch, create 'latest' tag
            type=raw,value=latest,enable=${{ github.event_name == 'workflow_dispatch' }}

      - name: Create VERSION file
        run: |
          VERSION="manual-$(date +%Y%m%d)-$(git rev-parse --short HEAD)"
          # If the trigger is a tag, get version from tag
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            # remove 'v' prefix from tag name
            VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//')
          fi
          echo "Using version: $VERSION"
          echo $VERSION > VERSION
          echo "VERSION file content:"
          cat VERSION

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Enable cache to speed up future builds
          cache-from: type=gha
          cache-to: type=gha,mode=max 